### ISSUE TITLE
Copy pasted the readme example to test. Keeps growing.

### ISSUE THREAD

**Issue by mokhosh** [asantibanez/livewire-charts#1]
I'm not sure why this keeps growing.

![Oct-23-2020 22-46-09](https://user-images.githubusercontent.com/6499685/97044867-9cc43180-1581-11eb-83ad-6378be1a5949.gif)

**Comment by mokhosh** [comment]
Just copy pasted the example into https://github.com/asantibanez/livewire-charts-demo and the same thing happens unless you give the parent an `style="height:100px"`

**Comment by asantibanez** [comment]
Hi @mokhosh ! Thanks for the report. Ran into this issue myself the other day. Putting a fix today. 👍

**Comment by asantibanez** [comment]
Resolved in v1.2.0

**Comment by pascallieverse** [comment]
This issue still remains in 1.2.0 building a simple line chart:

`        $data['quotationsADay'] = (new LineChartModel())
            ->setTitle('quotations each day')
            ->addPoint('18-10-2020', 200)
            ->addPoint('19-10-2020', 100)
            ->addPoint('20-10-2020', 300)
            ->addPoint('21-10-2020', 200)
            ->addPoint('22-10-2020', 230)
            ->addPoint('23-10-2020', 280)
            ->addPoint('24-10-2020', 210);`

`<livewire:livewire-line-chart
        :line-chart-model="$quotationsADay"
    />`

**Comment by asantibanez** [comment]
Hello again @mokhosh @pascallieverse 

I've addressed this in the README.md. https://github.com/asantibanez/livewire-charts#troubleshooting

As @mokhosh points out, you need to add a fixed height to the wrapping parent container to make the chart render and work properly.

**Comment by fadilbjm** [comment]
i have same issue but i finally fixed it .
it's simple you must lock the height with specific px
