### ISSUE TITLE
init is not defined

### ISSUE THREAD

**Issue by alexvolley** [asantibanez/livewire-charts#30]
**Describe the bug**
After the latest update to v2.3.0 I am now just getting a lot of init is not defined errors in my console. This was working fine on 2.2.0.

![image](https://user-images.githubusercontent.com/9260536/108551703-34475000-72e8-11eb-816d-e70417a9c07f.png)

The code itself that I am using has not changed its just the version, am i supposed to do anything different here.

![image](https://user-images.githubusercontent.com/9260536/108552245-f139ac80-72e8-11eb-9a84-f3742b71b408.png)

**Comment by asantibanez** [comment]
Hi @alexvolley !

Run `php artisan view:clear`. That should solve the issue. The `init` method was introduce in a refactor and your views might be out of sync with the new ones. 

Hope that helps.

**Comment by alexvolley** [comment]
omg... im such an idiot... thank you so much.

**Comment by mokhosh** [comment]
I did `view:clear` but i'm still getting `init not defined` any ideas why that might be?

**Comment by jkniest** [comment]
@mokhosh I had the same problem. 

You'll need to remove the `public/vendor/livewire-charts` folder manually and then execute the `php artisan vendor:publish --tag=livewire-charts:public` again. 

Somehow it didn't override the old javascript code, so the `init` method didn't exists.

Hope this helps!

**Comment by mokhosh** [comment]
Thanks @jkniest that did help.
